import { mkdir, readFile, copyFile, cp, rm, access } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// Rebuilt from scratch each time so a file removed from the list below
// (e.g. a superseded script) doesn't linger as a stale, unreferenced copy.
await rm(resolve(root, 'dist'), { recursive: true, force: true });

// wallet-widget/ is generated by `npm run build:widget` (see scripts/build-widget.mjs)
// and must exist before this runs — see the "build" npm script, which runs both in order.
try {
  await access(resolve(root, 'wallet-widget/main.js'));
} catch {
  throw new Error('wallet-widget/main.js is missing. Run `npm run build:widget` first (or `npm run build`).');
}

// Only public site assets are copied. Environment files never enter the output.
// wallet-widget/main.js and main.css are the two entries referenced by
// href/src in the HTML below; the rest of wallet-widget/ (RainbowKit's
// lazily-imported, per-wallet connector chunks) is copied wholesale further
// down since those filenames are content-hashed and unpredictable.
const files = ['index.html', 'trade.html', 'vault.html', 'lending.html', 'portfolio.html', 'css/styles.css', 'css/trade.css', 'css/vault.css', 'css/lending.css', 'css/portfolio.css', 'js/main.js', 'js/trade.js', 'js/chart-datafeed.js', 'js/home-prices.js', 'js/token-icons.js', 'js/chart-types.js', 'js/lending.js', 'js/portfolio.js', 'img/hype-logo.jpg', 'wallet-widget/main.js', 'wallet-widget/main.css'];
// Classic (non-module) hand-authored scripts are parsed here as a syntax
// check; wallet-widget/main.js is an ES module Vite already validated.
const classicScripts = ['js/main.js', 'js/trade.js', 'js/chart-datafeed.js', 'js/home-prices.js', 'js/token-icons.js', 'js/chart-types.js', 'js/lending.js', 'js/portfolio.js'];
for (const file of files) {
  const source = await readFile(resolve(root, file), 'utf8');
  if (classicScripts.includes(file)) new Script(source, { filename: file });
  if (file.endsWith('.html')) {
    for (const match of source.matchAll(/(?:href|src)="([^"#][^"]*)"/g)) {
      const reference = match[1].split('#')[0];
      if (/^https?:\/\//.test(reference)) continue;
      if (!files.includes(reference)) throw new Error(`Missing public asset: ${file} → ${reference}`);
    }
  }
  const destination = resolve(root, 'dist', file);
  await mkdir(dirname(destination), { recursive: true });
  await copyFile(resolve(root, file), destination);
}

await cp(resolve(root, 'wallet-widget'), resolve(root, 'dist/wallet-widget'), { recursive: true });

console.log(`Validated and prepared 5 pages, ${files.length - 5} hand-authored CSS/JS assets, and wallet-widget/ in dist/.`);
