import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';
import { createPublicClient, createWalletClient, http, formatEther } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { arcTestnet } from '../src/wallet-widget/chain.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function compile() {
  const source = readFileSync(resolve(root, 'contracts/RailflowAMM.sol'), 'utf8');
  const input = { language: 'Solidity', sources: { 'RailflowAMM.sol': { content: source } }, settings: { optimizer: { enabled: true, runs: 200 }, outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } } } };
  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  for (const error of output.errors || []) console[error.severity === 'error' ? 'error' : 'warn'](error.formattedMessage);
  if ((output.errors || []).some((error) => error.severity === 'error')) throw new Error('Solidity compilation failed.');
  const contract = output.contracts['RailflowAMM.sol'].RailflowAMM;
  return { abi: contract.abi, bytecode: '0x' + contract.evm.bytecode.object };
}

async function main() {
  const privateKey = process.env.DEPLOYER_PRIVATE_KEY;
  if (!privateKey) throw new Error('Set DEPLOYER_PRIVATE_KEY in .env first.');
  const account = privateKeyToAccount(privateKey.startsWith('0x') ? privateKey : '0x' + privateKey);
  const { abi, bytecode } = compile();
  const transport = http(process.env.ARC_RPC_URL || 'https://rpc.testnet.arc.io');
  const publicClient = createPublicClient({ chain: arcTestnet, transport });
  const walletClient = createWalletClient({ account, chain: arcTestnet, transport });
  const balance = await publicClient.getBalance({ address: account.address });
  console.log('Deployer:', account.address, '(' + formatEther(balance) + ' USDC for gas)');
  if (balance === 0n) throw new Error('Deployer has no Arc Testnet USDC for gas.');
  const hash = await walletClient.deployContract({ abi, bytecode });
  console.log('Transaction sent:', hash);
  const receipt = await publicClient.waitForTransactionReceipt({ hash });
  if (receipt.status !== 'success' || !receipt.contractAddress) throw new Error('AMM deployment failed.');
  writeFileSync(resolve(root, 'src/wallet-widget/ammAbi.js'), '// Auto-generated by scripts/deploy-amm.mjs.\nexport const ammAbi = ' + JSON.stringify(abi, null, 2) + ';\n');
  writeFileSync(resolve(root, 'src/wallet-widget/amm.js'), '// Auto-generated deployment config.\nexport const AMM_ADDRESS = \'' + receipt.contractAddress + '\';\n');
  console.log('Deployed RailflowAMM at:', receipt.contractAddress);
  console.log('Arcscan: https://testnet.arcscan.app/address/' + receipt.contractAddress);
}

main().catch((error) => { console.error(error.message || error); process.exit(1); });
