import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';
import { createPublicClient, createWalletClient, http, formatEther } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { arcTestnet } from '../src/wallet-widget/chain.js';

// Compiles and deploys contracts/RailflowVault.sol to Arc Testnet using a
// key you provide — this project has no access to your wallet, so you run
// this yourself:
//
//   1. Put a testnet-only private key in .env as DEPLOYER_PRIVATE_KEY
//      (never your real wallet's key; .env is already gitignored).
//   2. Fund that address with Arc Testnet USDC for gas (it's the chain's
//      native currency) via https://faucet.circle.com/.
//   3. Run `npm run deploy:vault`.
//
// On success this also overwrites src/wallet-widget/vaultAbi.js with the
// ABI actually compiled here, so the frontend can never drift from what's
// really deployed. Add the printed address to .env as
// NEXT_PUBLIC_VAULT_ADDRESS afterwards (and rebuild) to wire it up.

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function compile() {
  const source = readFileSync(resolve(root, 'contracts/RailflowVault.sol'), 'utf8');
  const input = {
    language: 'Solidity',
    sources: { 'RailflowVault.sol': { content: source } },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
    },
  };
  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  const errors = output.errors || [];
  errors.forEach((e) => console[e.severity === 'error' ? 'error' : 'warn'](e.formattedMessage));
  if (errors.some((e) => e.severity === 'error')) {
    throw new Error('Solidity compilation failed, see errors above.');
  }
  const contract = output.contracts['RailflowVault.sol'].RailflowVault;
  return { abi: contract.abi, bytecode: '0x' + contract.evm.bytecode.object };
}

function writeAbi(abi) {
  const banner = '// Auto-generated by scripts/deploy-vault.mjs from contracts/RailflowVault.sol.\n// Do not hand-edit — redeploy (npm run deploy:vault) to regenerate.\n';
  const content = banner + 'export const vaultAbi = ' + JSON.stringify(abi, null, 2) + ';\n';
  writeFileSync(resolve(root, 'src/wallet-widget/vaultAbi.js'), content);
}

async function main() {
  const privateKey = process.env.DEPLOYER_PRIVATE_KEY;
  if (!privateKey) {
    throw new Error('Set DEPLOYER_PRIVATE_KEY in .env first — a testnet-only key funded with Arc Testnet USDC for gas. Never use a key that holds real funds.');
  }
  const account = privateKeyToAccount(privateKey.startsWith('0x') ? privateKey : '0x' + privateKey);

  console.log('Compiling contracts/RailflowVault.sol...');
  const { abi, bytecode } = compile();

  const publicClient = createPublicClient({ chain: arcTestnet, transport: http() });
  const walletClient = createWalletClient({ account, chain: arcTestnet, transport: http() });

  const balance = await publicClient.getBalance({ address: account.address });
  console.log('Deployer:', account.address, '(' + formatEther(balance) + ' USDC for gas)');
  if (balance === 0n) {
    throw new Error('Deployer address has 0 USDC on Arc Testnet — fund it via https://faucet.circle.com/ before deploying.');
  }

  console.log('Deploying RailflowVault to Arc Testnet...');
  const hash = await walletClient.deployContract({ abi, bytecode });
  console.log('Transaction sent:', hash);
  const receipt = await publicClient.waitForTransactionReceipt({ hash });
  if (receipt.status !== 'success' || !receipt.contractAddress) {
    throw new Error('Deployment transaction failed. Receipt: ' + JSON.stringify(receipt));
  }

  writeAbi(abi);
  console.log('\nDeployed RailflowVault at:', receipt.contractAddress);
  console.log('View it on Arcscan: https://testnet.arcscan.app/address/' + receipt.contractAddress);
  console.log('\nAdd this to .env, then run `npm run build`:');
  console.log('NEXT_PUBLIC_VAULT_ADDRESS=' + receipt.contractAddress);
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
